import java.io.*;
import java.util.*;

class Main {
    static Scanner in = new Scanner(System.in);
    static PrintWriter out = new PrintWriter(new OutputStreamWriter(System.out));


    public static void main(String[] args) throws Exception {
        String s = in.next();
        int n = in.nextInt();
        double x = in.nextDouble();
        boolean b = in.nextBoolean();


        out.flush();
    }
}